pipeline:
  name: testingggg
  identifier: testingggg
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Test_build
        identifier: Test_build
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |
                      echo "hello"
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: Git_RK
                    cloneDirectory: MavenWebAppTest
                    build:
                      type: branch
                      spec:
                        branch: master
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: |
                      echo "Current directory:"
                      pwd

                      echo "Files in workspace:"
                      ls -la

                      echo "Files inside cloned repository:"
                      ls -la MavenWebAppTest
              - step:
                  type: Run
                  name: Build
                  identifier: Build
                  spec:
                    shell: Sh
                    command: |-
                      - step:
                          type: Run
                          name: Maven Test
                          identifier: Maven_Test
                          spec:
                            shell: Sh
                            image: maven:3.9.9-eclipse-temurin-17
                            command: |
                              cd MavenWebAppTest
                              mvn clean test
